{% set name = "dropstackframe" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f0b2724e729fee66d78ffaf15cfa1764e3a480f8c90f8dd6ed0e2b26c841c1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry-core
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - dropstackframe
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jesnie/dropstackframe
  summary: 'A python library for dropping stack frames.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - westinhuang
